### ISSUE TITLE
document example for multiple playerNames

### ISSUE THREAD

**Issue by schneefux** [schneefux/python-gamelocker#3]

**Comment by iAm-Kashif** [comment]
Attached .py code and output image.

[getPlayerStats.zip](https://github.com/schneefux/python-gamelocker/files/851830/getPlayerStats.zip)

**Comment by iamkashz** [comment]
Attached .py and output image. 👍 

[getPlayerStats.zip](https://github.com/schneefux/python-gamelocker/files/851833/getPlayerStats.zip)

**Comment by schneefux** [comment]
added in 49f286a
Thanks! 🎉
